### ISSUE TITLE
small wording consistency issue — ch 6 exercises

### ISSUE THREAD

**Issue by jonathanichikawa** [jonathanichikawa/for-all-x#2]
![image](https://user-images.githubusercontent.com/47093353/52436486-44a57d00-2ac9-11e9-9f7d-72057063ff58.png)

Singular/plural conventions are inconsistent. 9 should probably be 'disjunctions' (or maybe change all others to singular.

**Comment by lauragreenstreet** [comment]
Since there were many examples using the plural, I changed 'disjunction' in example 9 to 'disjunctions'.
