### ISSUE TITLE
Aristotelian syllogisms

### ISSUE THREAD

**Issue by jonathanichikawa** [jonathanichikawa/for-all-x#24]
Chapter 8, Practice Questions E Darii and Datisi look exactly the same — is this right? Likewise for Ferison and Ferio. I don't actually know these terms, I or someone needs to dig into it and see what's going on.

**Comment by automaton777** [comment]
I've made a pull request with a number of corrections to the Part E exercises on syllogistic figures in Chapter 8. Here is documentation of my reasoning for the changes.

Darii is correct, but Datisi is stated incorrectly. I have corrected it to
All Bs are Cs/**Some B is A**//Some A is C

For reference, take the table in section 5.4 of this SEP article https://plato.stanford.edu/entries/aristotle-logic/ and, keeping in mind the note about notation in 4.3.2, substitute [A/b], [B/c], [C/a]. You will obtain my statement of Datisi.

Bocardo is also incorrect. My correction:
Some B is not C/**All Bs are As**// Some A is not C
This is obtained from table 5.4 by substituting [A/b], [B/c], [C/a].
The version prior to my correction is invalid in syllogistic and QL- countermodel:
A={m}, B={m,n}, C={m}
Note that countermodels for QL where every predicate has a nonempty extension are also countermodels for syllogistic.

Cemestres appears to be an invention of P. D. Magnus and is not valid in syllogistic or QL. See 5.5 of the SEP article - one of Aristotle's metatheoretic results in Prior Analytics is that no syllogistic deduction can have two negative premises (negative premises have either the form "No A is B" or "Some A is not B"). Countermodel to Cemestres: A={m}, B={n}, C={m}.

I have replaced Cemestres with the valid **Camestres** (which I've placed in alphabetical order in the list):
All Cs are Bs/No As are Bs//No As are Cs.
My version is obtained from SEP table 5.4 with [A/c], [B/a], [C/b].

Likewise, Disamis is incorrectly stated. I have corrected it to:
Some B is C/**All Bs are As**//Some A is C
Obtainable from SEP table 5.4 with [A/b], [B/c], [C/a].
Countermodel to the earlier version: A={m}, B={m,n}, C={n}.

Similarly for Ferison. I have corrected it to
No Bs are Cs/**Some B is A**//Some A is not C.
Obtainable from table 5.4 with [A/b], [B/c], [C/a].
The earlier version was just a copy of Ferio, which is correctly stated.

I have checked all the syllogisms and see no other errors.

**Comment by automaton777** [comment]
There's also the more minor issue that "syllogistic figures" does not standardly refer to argument forms such as the 16 listed in the exercises, but instead to the 3 or 4 possible orders in which the major and minor terms appear in argument forms (3 for Aristotle, 4 for later commentators - this depends on some metatheoretic considerations). See 5.1 of the SEP article.

Thus, I've made another commit to correct "These are syllogistic figures identified by Aristotle and his successors," to "These are syllogistic **argument forms** identified by Aristotle and his successors". The standard terminology for syllogistic argument forms is "moods" (see section 5.4 of SEP), but "argument forms" is accurate and self-explanatory.
