### ISSUE TITLE
reiteration rule shouldn't be basic

### ISSUE THREAD

**Issue by jonathanichikawa** [jonathanichikawa/for-all-x#4]
The "Reiteration" natural deduction rule is listed as a basic, not a derived, rule. This is unnecessary — it can be derived via or-introduction, negation elimination, and negation elimination. Need to add a discussion of the fact to the derived rules section, and move the R rule from the basic page to the derived page in the appendix.

**Comment by jonathanichikawa** [comment]
I think I was mistaken about this. Given the way our reductio rules are written, I don't think we can derive R from the introduction and elimination rules after all. I had been thinking along these lines:
![image](https://user-images.githubusercontent.com/47093353/52977755-5a495b00-3383-11e9-9495-a2101ba10b27.png)

But this is a mistake; line 4 would have needed to reference the double negation, which is not what we have on 1.

So unless/until I figure out how to derive R, I'll leave it as basic.

**Comment by Nico314159** [comment]
You can derive R as follows:

1. φ
2. φ ∧ φ    (∧I, 1, 1)
3. φ           (∧E, 2)

**Comment by jonathanichikawa** [comment]
I made this change.
