### ISSUE TITLE
Inconsistent appendixes in table of contents

### ISSUE THREAD

**Issue by jonathanichikawa** [jonathanichikawa/for-all-x#7]
A and B have their labels in the ToC, but C doesn't. This should be made consistent.

![image](https://user-images.githubusercontent.com/47093353/52980098-633f2a00-338d-11e9-9e52-3804eccdedf1.png)

**Comment by lauragreenstreet** [comment]
Fixed. In the process, I changed some spacing around the appendix titles. Let me know if you think it looks too dense.
