### ISSUE TITLE
ND rules subheadings in Quick Reference

### ISSUE THREAD

**Issue by jonathanichikawa** [jonathanichikawa/for-all-x#8]
There are two pages of natural deduction rules in Appendix C. These should be in the following subcategories:

**Natural Deduction Rules**
* Basic Rules
* Derived Rules
* Replacement Rules
* Quantifier Rules
* Identity Rules

At present, we don't have a label for basic rules, and "Natural Deduction Rules" is given in a smaller font than the other subcategories.

**Comment by lauragreenstreet** [comment]
Fixed.
